### ISSUE TITLE
Using on Github Pages

### ISSUE THREAD

**Issue by carlosedp** [jameshamann/jekyll-display-medium-posts#1]
How to use the plugin with the site hosted on Github pages where I can't set the environment variable?

Thanks

**Comment by mcred** [comment]
@carlosedp Github pages uses the `--safe` flag when building sites with Jekyll. This disallows all plugins that aren't white listed with github. You can work around this by using Travis CI with your own Jekyll build. I just did this and wrote about how I did it [here](https://medium.com/@mcred/supercharge-github-pages-with-jekyll-and-travis-ci-699bc0bde075). Hope this helps!
